class BookmarkRepository:
    def add() -> None: ...
    def update() -> None: ...
    def get_by_url() -> None: ...
    def get_by_id() -> None: ...
    def list_all() -> None: ...
    def increment_copy_count() -> None: ...
